/* Types para Token */
export const VERIFICAR_TOKEN = "VERIFICAR_TOKEN";
export const TOKEN_EXISTE = "TOKEN_EXISTE";
export const TOKEN_NO_EXISTE = "TOKEN_NOS_EXISTE";
export const ELIMINAR_TOKEN = "ELIMINAR_TOKEN";

/* Types para login */
export const LOGIN_START = "LOGIN_START";
export const LOGIN_EXITOSO = "LOGIN_EXITOSO";
export const LOGIN_ERROR = "LOGIN_ERROR";

/* Types para menu */
export const MOSTRAR_MENU = "MOSTRAR_MENU";
export const OCULTAR_MENU = "OCULTAR_MENU";

/* types para admins */
/* Descargar admins */
export const DESCARGAR_ADMINS = "DESCARGAR_ADMINS";
export const OBTENER_ADMINS_EXITO = "OBTENER_ADMINS_EXITO";
export const OBTENER_ADMINS_ERROR = "OBTENER_ADMINS_ERROR";
/* Agregar Admins */
export const AGREGAR_ADMIN = "AGREGAR_ADMIN";
export const AGREGAR_ADMIN_SUCCESS = "AGREGAR_ADMIN_SUCCESS";
export const AGREGAR_ADMIN_ERROR = "AGREGAR_ADMIN_ERROR";
/* Editar Admins */
export const OBTENER_ADMIN_EDITAR = "OBTENER_ADMIN_EDITAR";
export const ADMIN_EDITAR = "ADMIN_EDITAR";
export const ADMIN_EDITAR_EXITO = "ADMIN_EDITAR_EXITO";
export const ADMIN_EDITAR_ERROR = "ADMIN_EDITAR_ERROR";
/* Eliminar Admins */
export const ADMIN_ELIMINAR = "ADMIN_ELIMINAR";
export const ADMIN_ELIMINAR_EXITO = "ADMIN_ELIMINAR_EXITO";
export const ADMIN_ELIMINAR_ERROR = "ADMIN_ELIMINAR_ERROR";
export const OCULTAR_ALERTA = "OCULTAR_ALERTA";

/* types para PROFs */
/* Descargar PROFs */
export const DESCARGAR_PROFS = "DESCARGAR_PROFS";
export const OBTENER_PROFS_SUCCESS = "OBTENER_PROFS_SUCCESS";
export const OBTENER_PROFS_ERROR = "OBTENER_PROFS_ERROR";
/* Agregar PROFs */
export const AGREGAR_PROF = "AGREGAR_PROF";
export const AGREGAR_PROF_SUCCESS = "AGREGAR_PROF_SUCCESS";
export const AGREGAR_PROF_ERROR = "AGREGAR_PROF_ERROR";
/* Editar PROFs */
export const OBTENER_PROF_EDITAR = "OBTENER_PROF_EDITAR";
export const PROF_EDITAR = "PROF_EDITAR";
export const PROF_EDITAR_SUCCESS = "PROF_EDITAR_SUCCESS";
export const PROF_EDITAR_ERROR = "PROF_EDITAR_ERROR";
/* Eliminar PROFs */
export const PROF_ELIMINAR = "PROF_ELIMINAR";
export const PROF_ELIMINAR_SUCCESS = "PROF_ELIMINAR_SUCCESS";
export const PROF_ELIMINAR_ERROR = "PROF_ELIMINAR_ERROR";

/* types para MATERIAs */
/* Descargar MATERIAs */
export const DESCARGAR_MATERIAS = "DESCARGAR_MATERIAS";
export const OBTENER_MATERIAS_SUCCESS = "OBTENER_MATERIAS_SUCCESS";
export const OBTENER_MATERIAS_ERROR = "OBTENER_MATERIAS_ERROR";
/* Agregar MATERIAs */
export const AGREGAR_MATERIA = "AGREGAR_MATERIA";
export const AGREGAR_MATERIA_SUCCESS = "AGREGAR_MATERIA_SUCCESS";
export const AGREGAR_MATERIA_ERROR = "AGREGAR_MATERIA_ERROR";
/* Editar MATERIAs */
export const OBTENER_MATERIA_EDITAR = "OBTENER_MATERIA_EDITAR";
export const MATERIA_EDITAR = "MATERIA_EDITAR";
export const MATERIA_EDITAR_SUCCESS = "MATERIA_EDITAR_SUCCESS";
export const MATERIA_EDITAR_ERROR = "MATERIA_EDITAR_ERROR";
/* Eliminar MATERIAs */
export const MATERIA_ELIMINAR = "MATERIA_ELIMINAR";
export const MATERIA_ELIMINAR_SUCCESS = "MATERIA_ELIMINAR_SUCCESS";
export const MATERIA_ELIMINAR_ERROR = "MATERIA_ELIMINAR_ERROR";

/* types para ALUMNOs */
/* Descargar ALUMNOs */
export const DESCARGAR_ALUMNOS = "DESCARGAR_ALUMNOS";
export const OBTENER_ALUMNOS_SUCCESS = "OBTENER_ALUMNOS_SUCCESS";
export const OBTENER_ALUMNOS_ERROR = "OBTENER_ALUMNOS_ERROR";
/* Agregar ALUMNOs */
export const AGREGAR_ALUMNO = "AGREGAR_ALUMNO";
export const AGREGAR_ALUMNO_SUCCESS = "AGREGAR_ALUMNO_SUCCESS";
export const AGREGAR_ALUMNO_ERROR = "AGREGAR_ALUMNO_ERROR";
/* Editar ALUMNOs */
export const OBTENER_ALUMNO_EDITAR = "OBTENER_ALUMNO_EDITAR";
export const ALUMNO_EDITAR = "ALUMNO_EDITAR";
export const ALUMNO_EDITAR_SUCCESS = "ALUMNO_EDITAR_SUCCESS";
export const ALUMNO_EDITAR_ERROR = "ALUMNO_EDITAR_ERROR";
/* Eliminar ALUMNOs */
export const ALUMNO_ELIMINAR = "ALUMNO_ELIMINAR";
export const ALUMNO_ELIMINAR_SUCCESS = "ALUMNO_ELIMINAR_SUCCESS";
export const ALUMNO_ELIMINAR_ERROR = "ALUMNO_ELIMINAR_ERROR";

/* Types para asignar materias a profes */
export const AGREGAR_ASIGNACION = "AGREGAR_ASIGNACION";
export const AGREGAR_ASIGNACION_EXITO = "AGREGAR_ASIGNACION_EXITO";
export const AGREGAR_ASIGNACION_ERROR = "AGREGAR_ASIGNACION_ERROR";
export const AGREGAR_ASIGNACION_ERRORES = "AGREGAR_ASIGNACION_ERRORES";

/* types para CALIFICACIONESS*/
/* Descargar CALIFICACIONESS*/
export const OBTENER_ALUMNOS_CALIFICAR = "OBTENER_ALUMNOS_CALIFICAR";

export const OBTENER_CALIFICACIONES = "OBTENER_CALIFICACIONES";
export const OBTENER_CALIFICACIONES_EXITO = "OBTENER_CALIFICACIONES_EXITO";
export const OBTENER_CALIFICACIONES_ERROR = "OBTENER_CALIFICACIONES_ERROR";
export const AGREGAR_CALIFICACIONES = "AGREGAR_CALIFICACIONES";
export const AGREGAR_CALIFICACIONES_EXITO = "AGREGAR_CALIFICACIONES_EXITO";
export const AGREGAR_CALIFICACIONES_ERROR = "AGREGAR_CALIFICACIONES_ERROR";

/* Nueva cvuenta actions */
export const OBTENER_NUEVA_CUENTA = "OBTENER_NUEVA_CUENTA";
export const NUEVA_CUENTA_EXITO = "NUEVA_CUENTA_EXITO";
export const NUEVA_CUENTA_ERROR = "NUEVA_CUENTA_ERROR";
